### PR TITLE
Implement dummy U-Report API

### PR DESCRIPTION
**Pull request by justinvdm**
This will make the app tests easier to read and write, and will give us the option of demoing against the dummy api, which can be quite convenient.

### CODE REVIEW

**Comment by justinvdm** [comment]
@hodgestar Ready for review. Its fairly small and simple. I ended up making the DummyUReportApi just have the same methods as UReportApi, but as stubs. The stubs use sinon, but the stub's result is wrapped as `Q(result).delay(0)` to prevent subtle promise bugs.

This means we can use the dummy api in some way like this:

``` javascript
tester.setup(function() {
    ureport
        .ureporters()
        .reports.submit.withArgs('report text')
        .returns({
            accepted: true,
            response: 'Thank you for your report'
        });
});
```

**Comment by justinvdm** [comment]
@hodgestar Hmm, just realised that we need to find some way of checking what is passed to `ureporters()` and `poll()`. I've got an idea, but first want to know if you are okay with the approach I am taking.

**Comment by hodgestar** [comment]
Couple of thoughts:
- We don't currently make `sinon` available inside production.
- Something needs to tell the stubs what to return if we're using this as a demo thing -- I'm not clear on what the plan for that is.
- I'm broadly okay with the plan, but we'll need to thoroughly test the real UreportApi using fixtures ideally taken from the UReport API test instance we've been given access to.
- We'll also need to test that the real UreportApi and the DummyUreportApi do the same thing. Maybe the best way to do this is to in the rests of the real UreportApi, assert that the dummy version returns the same thing as the real version does for each fixture test?

**Comment by justinvdm** [comment]
Erm, closed this by mistake, sorry :)

**Comment by justinvdm** [comment]
@hodgestar Cool, answers to your points:

> We don't currently make sinon available inside production.

True, we will either need to make it available, or concat sinon for the demo build of the app.

> Something needs to tell the stubs what to return if we're using this as a demo thing -- I'm not clear on what the plan for that is.

This is quite similar to the code example I gave above. Basically, we will have a `demo.js` script that will look something like this:

``` javascript
ureport
    .ureporters()
    .reports.submit.withArgs('report text')
    .returns({
        accepted: true,
        response: "Thank you for your report"
    });

ureport
    .ureporters()
    .reports.submit.withArgs('bad report text')
    .returns({
        accepted: false,
        response: "Sorry, we did not understand your report"
    });
```

> I'm broadly okay with the plan, but we'll need to thoroughly test the real UreportApi using fixtures ideally taken from the UReport API test instance we've been given access to.

Good idea, we can change the `UReportApi` tests to use these fixtures. 

> We'll also need to test that the real UreportApi and the DummyUreportApi do the same thing. Maybe the best way to do this is to in the rests of the real UreportApi, assert that the dummy version returns the same thing as the real version does for each fixture test?

I'm a bit confused about this point. They don't do the same thing, since `DummyUReportApi` just returns what we tell it to. Sorry if this something obvious, could you explain?

I'd like to avoid having to add http fixtures for each interaction test, but otherwise I'm also happy to try alternative approaches.

**Comment by hodgestar** [comment]
The past approach to using fixtures has been to add a largish set of fixtures at the start (or at least define them at the start) and then rely on them as needed from individual tests.

**Comment by justinvdm** [comment]
Closing this in favor of #12

**Comment by justinvdm** [comment]
Open again and ready for review.

To maybe give some clarity, our `demo.js` module will look something like this:

``` javascript
ureport
    .ureporters
    .poll
    .responses.submit.returns({
        accepted: true,
        response: 'This is the default response'
    });

ureport
    .ureporters
    .poll.withArgs('123')
    .responses.submit.withArgs({
        response: 'response text'
    })
    .returns({
        accepted: true,
        response: "This the response for poll '123' when given 'response text'"
    });

ureport
    .ureporters
    .poll.withArgs('456')
    .responses.submit.withArgs({
        response: "bad response text"
    })
    .returns({
        accepted: false,
        response: "This is the response for poll '456' when given 'bad response text'"
    });

...
```

**Comment by justinvdm** [comment]
@hodgestar If we do end up using this, we should definitely test `UReportApi` against real data we get from the api instance (as you suggested earlier).

**Comment by hodgestar** [comment]
It looks like some of the dummy stuff ended up in `vumi-ureport.js` but otherwise this looks good.

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
