### PR TITLE
Implement dummy U-Report API that works off http fixtures

### PR DESCRIPTION
**Pull request by justinvdm**
Same as #11, except based on http fixtures instead of stubbyness.

### CODE REVIEW

**Comment by justinvdm** [comment]
@hodgestar Ready for review.

I decided to leave the fixtures for another PR (or we can add them as we go).

I'm really not confident on this code, the approach doesn't feel natural to me. `DummyUReportApi` feels like a weird wrapper around `DummyApi`'s http fixture infrastructure to make it work better with the `UReportApi`. I'm up for alternatives. Let me know what you think.

**Comment by justinvdm** [comment]
@hodgestar I'm wondering if we maybe need a way of dynamically adding fixtures based on the user address given to `UReportApi`. We would need that in order to demo properly.

If we want that, then maybe `DummyUReportApi` should be mimicking `UReportApi` like it was in #11, but instead dynamically add http fixtures based on the ussr addr given to `UReportApi.ureporters()`. I'm really not too sure though, will wait to see what you think.

**Comment by justinvdm** [comment]
bump? :)

@hodgestar Really don't want to rush you on this, you've been reviewing way too much stuff for me, I just kind of need some input here before I can write tests for the app in #14. Happy to just make test stubs so long, just wanted to bring this PR back up in case it was forgotten or something.

**Comment by justinvdm** [comment]
Ah, about [this comment](https://github.com/praekelt/vumi-ureport/pull/12#issuecomment-34323066): maybe we could use string templating in the fixtures to be able to dynamically set the user addr in the http fixtures. That would be straight-forward to do, and would let us demo using the fixtures pretty easily (the only other way around it would be to hardcode the user addr we are using to demo). It would mean including another dependency for the templating, but we could include it in the demo build since its just for the demo.

Anyways, sorry for all the spam, will stop talking to myself now :)

**Comment by hodgestar** [comment]
The difficulty in doing this on top of fixtures (which I didn't foresee) is that which fixture is to be retrieved depends on variables we can specify in tests (e.g. MSISDN) but don't easily have a way to specify in production.

I see two approaches to fixing this:
- Return to a very dumb DummyReportApi like the ones I've written before where the methods return  fixed values or values that vary very simply with input parameters.
- Extend the current fixture based approach to somehow allow matching and selecting fixtures even though input is not exactly the same.

I think the former approach is less risky.

**Comment by justinvdm** [comment]
Closing in favor of #11

**Pull request closed without merging**
