### PR TITLE
Update to use toolkit's http api and resource changes

### PR DESCRIPTION
**Pull request by justinvdm**
Update to use the changes introduced in praekelt/vumi-jssandbox-toolkit#83.

### CODE REVIEW

**Comment by justinvdm** [comment]
Will need praekelt/vumi-jssandbox-toolkit#83, but ready for review.

**Comment by hodgestar** [comment]
Looks good. :+1: after 83 has landed.

**Comment by justinvdm** [comment]
@hodgestar Thanks for the reviews! Happy with this landing?

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
